name: ml_kit_object_detection
description: A Flutter project for object detection using Google ML Kit.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_object_detection: ^0.1.0
  camera: ^0.9.4+19
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
